name: gym_tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  # Estado
  bloc: ^9.1.0
  equatable: ^2.0.5
  # Persistencia de datos
  fl_chart: ^1.1.1
  floor: ^1.5.0
  # Framework Flutter
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  # Utilidades
  formz: ^0.8.0
  get_it: ^9.0.5
  go_router: ^17.0.0
  injectable: ^2.5.0
  intl: ^0.20.2
  # UI/UX
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  uuid: ^4.5.1

dev_dependencies:
  # Testing
  bloc_test: ^10.0.0
  # Generación de código
  build_runner: ^2.4.13
  floor_generator: ^1.5.0
  # Framework Flutter
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  # Testing adicional
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  patrol: ^3.12.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
